retails_project:
  outputs:
    dev:
      dbname: airflow
      host: postgres
      pass: airflow
      port: 5432
      schema: raw_retails_data
      threads: 1
      type: postgres
      user: airflow
  target: dev

