retails_project:
  outputs:
    dev:
      dbname: airflow15   #airflow
      host: postgres
      pass: airflow15  #airflow
      port: 5432
      schema: ''
      threads: 1
      type: postgres
      user: airflow15  #airflow
  target: dev

